"""Simulate and visualize Field Oriented Control core transforms.

Run the core transforms to convert between 3-phase motor and 2-phase direct-quadrature space.
Use polars DataFrame and Altair Chart to plot the waveforms.
"""

from altair import Chart, ConcatChart, HConcatChart
from mlx.core import linspace, pi, sin
from numpy import stack
from polars import DataFrame, col
from polars.selectors import matches

from .core import clarke, inv_clarke, inv_park, park, svm


def control(v_bus: float = 48.0, i_pk: float = 10.0, k_p: float = 5.0) -> DataFrame:
    """Simulate a Field Oriented Control current loop.

    In a real-time system, a current reference (typically generated by an outer
    speed or position loop, with zero direct current and non-zero quadrature current)
    is injected into the current loop. Note that quadrature current creates torque while
    direct current induces cogging.

    Sensed current is read by ADC from the motor phases and transformed into direct-quatrature
    (DQ) current using the Clarke/Park transforms. Feedback error terms are calculated as the
    difference between reference and sensed current, fed into independent PI controllers to
    generate DQ voltage references, and transformed to phase voltages with Inverse Park/Clarke.

    Phase voltages are shifted and converted to duty-cycles using Space Vector Modulation (SVM).
    Duty-cycle can be mapped to GPIO and connected to input pins on a motor-driver chip for
    Pulse Width Modulation (PWM) control of the motor.

    In this simulated system an open-loop vector-equivalent is implemented. Core transforms
    are applied to generate duty-cycles as output from a sensed-current input vector.

    Parameters:
        v_bus: bus voltage (Volt)
        i_pk: peak sensed current (Amp)
        k_p: gain (Volt/Amp)

    Returns:
        data: waveform DataFrame.
    """
    # Simulate 3-phase sensed phase currents (i_a + i_b + i_c = 0).
    theta = linspace(0, 2 * pi, 100)  # elec angle (rad)
    i_a = i_pk * sin(theta)
    i_b = i_pk * sin(theta - 2 * pi / 3)

    # Park-Clarke transform.
    tmp_alpha, tmp_beta = clarke(i_a, i_b)
    i_d, i_q = park(tmp_alpha, tmp_beta, theta)

    # Apply proportional gain.
    v_d = k_p * i_d  # direct
    v_q = k_p * i_q  # quadrature

    # Inverse Park-Clarke transform.
    tmp_alpha, tmp_beta = inv_park(v_d, v_q, theta)
    v_a, v_b, v_c = inv_clarke(tmp_alpha, tmp_beta)

    # Space Vector Modulation.
    t_a, t_b, t_c = svm(v_a, v_b, v_c, v_bus)

    # Stack waveforms and labels into DataFrame.
    return DataFrame(
        data=stack([theta, i_a, i_b, v_d, v_q, t_a, t_b, t_c]),
        schema=["theta", "i_a", "i_b", "V_d", "V_q", "T_a", "T_b", "T_c"],
    )


def plot(df: DataFrame) -> ConcatChart | HConcatChart:
    """Plot DataFrame waveforms.

    Returns:
        Concatenated line Chart.
    """
    # Add i_c column using 3-phase relation: i_a + i_b + i_c == 0.
    df = df.with_columns([(-col("i_a") - col("i_b")).alias("i_c")])

    return (
        _line_chart(df, "i[_].", "theta", "current (Amp)")
        | _line_chart(df, "V[_].", "theta", "voltage (Volt)")
        | _line_chart(df, "T[_].", "theta", "duty cycle")
    )


def _line_chart(df: DataFrame, regex: str, idx: str, ylab: str) -> Chart:
    """Helper function to generate Chart from DataFrame.

    Match columns by regex selector, unpivot from wide to long format.
    Generate line plot with index (x) vs matched columns (y).

    Parameters:
        df: data in DataFrame.
        regex: column selector string.
        idx: index column string.
        ylab: plot y-label string.

    Returns:
        line plot Chart.
    """
    grplab: str = "var"  # group-by label

    return (
        Chart(
            df.unpivot(
                on=matches(regex),
                index=idx,
                value_name=ylab,
                variable_name=grplab,
            ),
        )
        .mark_line(tooltip=True)
        .encode(x=idx, y=ylab, color=grplab)  # ty: ignore
    )
